### ISSUE TITLE
Add PFAM's and TIGRFAM's

### ISSUE THREAD

**Issue by adityabandla** [cjneely10/MetaSanity#4]
Adding PFAM's & TIGRFAM's will make this a comprehensive tool for functional annotation

**Comment by cjneely10** [comment]
Good afternoon,

**MetaSanity** optionally incorporates `InterProScan-5.36-75.0` analyses into its pipeline, which completes the PFAM/TIGRFAM annotation. Instructions for integrating `InterProScan` into **MetaSanity** are available [here](https://github.com/cjneely10/MetaSanity/wiki/2-Installation)

I will go ahead and close this issue post since your suggestion is already a feature of MetaSanity.

Thank you for your post.
